sudo: false

language: node_js

node_js:
  - node

branches:
  only:
    - master
    - dev
# update yarn to the newest version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install
script:
  - yarn test

nofications:
  email: false
